service: "api-test"
useDotenv: true

provider:
  name: "aws"
  runtime: "nodejs14.x"
  memorySize: 128
  timeout: 3
  region: "ap-east-1"
  stage: ${opt:state, 'dev'}
  lambdaHashingVersion: 20201221
  versionFunctions: false
  apiGateway:
    shouldStartNameWithService: true
  httpApi:
    cors: true
  environment:
    NODE_ENV: ${opt:state, 'dev'}
    MONGO_USER: ${file(./config.${opt:state, 'dev'}.json):MONGO_USER}
    MONGO_PASSWORD: ${file(./config.${opt:state, 'dev'}.json):MONGO_PASSWORD}
    MONGO_DB_NAME: ${file(./config.${opt:state, 'dev'}.json):MONGO_DB_NAME}
    MONGO_HOST: ${file(./config.${opt:state, 'dev'}.json):MONGO_HOST}

functions:
  - "${file(endpoints/hello.yml)}"
  - "${file(endpoints/documents.yml)}"

plugins:
  - "serverless-offline"

custom:
  serverless-offline:
    httpPort: 6099
    host: 0.0.0.0